import { Readable } from 'node:stream';
import { pipeline } from 'node:stream/promises';
import { parseChatOutput, Snippet } from './parser';

import { resolveFilename, saveAll } from './saver';
import { ok } from './chalk';

export async function extractSnpipets(
  source: string | Readable,
  output?: string
): Promise<void> {
  let input: string;
  if (typeof source === 'string') {
    input = source;
  } else {
    input = await readStream(source);
  }

  if (!input) {
    console.error(
      'No input detected. Please pipe in some text to generate code from.'
    );
    return;
  }

  // get snippets from the output
  const snippets = parseChatOutput(input);

  printOverview(snippets, output);

  if (snippets.length === 0) {
    console.log(
      'No code snippets were generated by Cody. No files will be created or updated'
    );
    return;
  }

  await saveAll(snippets, output, (filepath) => {
    console.log(ok, `-> ${filepath}`);
  });
}

async function readStream(stream: Readable): Promise<string> {
  const chunks: any[] = [];

  await pipeline(stream, async (source) => {
    for await (const chunk of source) {
      chunks.push(chunk);
    }
  });

  return Buffer.concat(chunks).toString();
}

function printOverview(snippets: Array<Snippet>, targetFolder?: string): void {
  console.log(ok, 'Cody generated the following files:');
  const overview = snippets.map(({ filename, content }) => ({
    filename: resolveFilename(filename, targetFolder),
    lines: content.split('\n').length,
    exists: false,
  }));
  console.table(overview);
  console.log();
}
